// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgbuihywmuqgswspbckt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1nYnVpaHl3bXVxZ3N3c3BiY2t0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTc1MDYsImV4cCI6MjA2NTgzMzUwNn0.4SPRSk9xW2H5mJS0yrv3khiAYwwRKfKs3duOYZ3woLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);